CREATE DATABASE Exercicio_1_3;


USE Exercicio_1_3;


CREATE TABLE CLINICA (
 IdClinica INT PRIMARY KEY  IDENTITY,
 NomeClinica VARCHAR(20) NOT NULL,
 EnderecoClinica VARCHAR(50) NOT NULL,
);
 

CREATE TABLE DONO	 (
 IdDono INT PRIMARY KEY  IDENTITY,
 NomeDono VARCHAR(20) NOT NULL,
);
 

CREATE TABLE TIPOPET (
 IdTipopet INT PRIMARY KEY  IDENTITY,
 Tipo VARCHAR(50) NOT NULL,
);


CREATE TABLE VETERINARIO(
IdVeterinario INT PRIMARY KEY  IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES CLINICA(IdClinica),
Nomevet CHAR(15) NOT NULL 
);


CREATE TABLE RACAS(
IdRacas INT PRIMARY KEY  IDENTITY,
IdTipopet INT FOREIGN KEY REFERENCES TIPOPET(IdTipopet),
QualRaca CHAR(15) NOT NULL 
);


CREATE TABLE PET(
IdPet INT PRIMARY KEY  IDENTITY,
IdRacas INT FOREIGN KEY REFERENCES RACAS(IdRacas),
IdDono INT FOREIGN KEY REFERENCES DONO(IdDono),
NomePet CHAR(10) NOT NULL 
);


CREATE TABLE ATENDIMENTO(
IdAtendimento INT PRIMARY KEY  IDENTITY,
IdVeterinario INT FOREIGN KEY REFERENCES VETERINARIO(IdVeterinario),
IdPet INT FOREIGN KEY REFERENCES PET(IdPet),
Horario_Atendimento CHAR(20) NOT NULL
);
