SELECT Nomevet,EnderecoClinica 
FROM VETERINARIO
INNER JOIN CLINICA
ON VETERINARIO.IdClinica = CLINICA.IdClinica;

SELECT QualRaca 
FROM Racas
WHERE QualRaca 
LIKE 'S%'

SELECT Tipo 
FROM TIPOPET
WHERE TIPOPET.Tipo 
LIKE '%O'

SELECT NomeDono,Tipo 
FROM TIPOPET
INNER JOIN DONO
ON DONO.IdDono = DONO.IdDono



SELECT Horario_Atendimento, Nomevet, NomePet, Tipo, NomeDono, enderecoClinica  
FROM ATENDIMENTO
INNER JOIN VETERINARIO 
ON ATENDIMENTO.IdVeterinario = VETERINARIO.IdVeterinario
INNER JOIN PET
ON ATENDIMENTO.IdPet = PET.IdPet
INNER JOIN RACAS
ON PET.IdRacas = RACAS.IdRacas
INNER JOIN TIPOPET 
ON RACAS.IdTipoPet = TIPOPET.IdTipoPet
INNER JOIN DONO
ON PET.IdDono = DONO.IdDono
INNER JOIN CLINICA
ON VETERINARIO.IdClinica = CLINICA.IdClinica;


