CREATE DATABASE HealthClinic_Tarde

USE HealthClinic_Tarde

CREATE TABLE TipoUsuario 
(
IdTipoUsuario INT PRIMARY KEY  IDENTITY(1, 1),
NomeTipoUsuario VARCHAR (20) NOT NULL
);

CREATE TABLE Clinica
(
IdClinica INT PRIMARY KEY  IDENTITY(1, 1),
NomeFantasia VARCHAR(30) NOT NULL UNIQUE,
Endereco VARCHAR(30) NOT NULL UNIQUE,
HorarioFuncionamento CHAR(20) NOT NULL,
CNPJ CHAR(14) NOT NULL UNIQUE,
RazaoSocial VARCHAR (60) NOT NULL UNIQUE

)

CREATE TABLE Especialidade 
(
IdEspecialidade INT PRIMARY KEY  IDENTITY(1, 1),
NomeEspecialidade VARCHAR (20) NOT NULL
)

CREATE TABLE Usuario
(
IdUsuario INT PRIMARY KEY  IDENTITY(1, 1),
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario),
Email VARCHAR(256) NOT NULL,

)